name: image-search-poc-segmentation
dependencies:
- python=3.6
- pip
- pip:
  - numpy
  - scikit-image
  - simplejson
  - matplotlib
  - h5py
  - jupyter==1.0.0
  - opencv-python
  - Keras==2.0.8 
  - tensorflow==1.1.0
  - Cython==0.28.1
  - ijson==2.3
  - ujson
  - opencv-python
  - toolz==0.9.0

