name: image-similarity-fusion
dependencies:
- python=2.7
- pip
- pip:
  - toolz==0.9.0
  - ijson==2.3
  - backports.csv==1.0.5
  - backports.functools-lru-cache==1.4
  - cli-helpers==1.0.1
  - configparser==3.5.0
  - cycler==0.10.0
  - decorator==4.1.2
  - funcsigs==1.0.2
  - h5py==2.7.1
  - ijson==2.3
  - Keras==2.1.2
  - matplotlib==2.1.0
  - mock==2.0.0
  - networkx==2.0
  - numpy==1.13.3
  - olefile==0.44
  - opencv-python==3.3.0.10
  - pbr==3.1.1
  - Pillow==4.3.0
  - protobuf==3.5.0.post1
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.3
  - PyWavelets==0.5.2
  - PyYAML==3.12
  - scikit-image==0.13.1
  - scikit-learn==0.19.1
  - scipy==1.0.0
  - six==1.11.0
  - subprocess32==3.2.7
  - tabulate==0.8.2
  - tensorflow-gpu==1.1.0
  #- https://github.com/mind/wheels/releases/download/tf1.1-cpu/tensorflow-1.1.0-cp27-cp27mu-linux_x86_64.whl
  - terminaltables==3.1.0
  - Theano==1.0.1
  - Unidecode==0.4.21
  - Werkzeug==0.12.2
  - simplejson==3.13.2
